#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = ROOT / "templates" / "note_page.html"
NOTES_OVERVIEW_PATH = ROOT / "notes.html"
START_MARKER = "<!-- AUTO-NOTES:START -->"
END_MARKER = "<!-- AUTO-NOTES:END -->"
OVERVIEW_START_MARKER = "<!-- NOTES-PREVIEW:START -->"
OVERVIEW_END_MARKER = "<!-- NOTES-PREVIEW:END -->"
GENERATED_MARKER = "<!-- Generated by sync_tex_note.py -->"
EPOCH_CREATED = "1970-01-01T00:00:00+00:00"
NOTES_PREVIEW_LIMIT = 3

CATEGORY_CONFIG = {
    "dft": {
        "index_path": ROOT / "notes" / "dft" / "index.html",
        "index_href": "/notes/dft/index.html",
        "label": "notes on DFT calculations",
        "overview_label": "DFT calculations",
    },
    "tb": {
        "index_path": ROOT / "notes" / "tb" / "index.html",
        "index_href": "/notes/tb/index.html",
        "label": "notes on Tight-binding models",
        "overview_label": "Tight-binding calculations",
    },
    "other": {
        "index_path": ROOT / "notes" / "other" / "index.html",
        "index_href": "/notes/other/index.html",
        "label": "other notes",
        "overview_label": "Other notes",
    },
}

LINK_RE = re.compile(r'<a\s+href="([^"]+)">\s*(.*?)\s*</a>', re.IGNORECASE | re.DOTALL)
LI_RE = re.compile(r"<li\b([^>]*)>(.*?)</li>", re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
UL_RE = re.compile(r"<ul\b[^>]*>.*?</ul>", re.IGNORECASE | re.DOTALL)


@dataclass
class NoteEntry:
    slug: str
    title: str
    created: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert TeX notes to HTML pages and update category index."
    )
    parser.add_argument("--category", required=True, choices=sorted(CATEGORY_CONFIG.keys()))
    parser.add_argument("--source", required=True, help="Path to .tex source file")
    parser.add_argument("--title", required=True, help="Display title in index and note page")
    parser.add_argument("--slug", required=True, help="Output file slug (without .html)")
    return parser.parse_args()


def validate_slug(slug: str) -> None:
    stripped = slug.strip()
    if not stripped:
        raise ValueError("slug 不能为空。")
    if stripped.endswith(".html"):
        raise ValueError("slug 不需要带 .html 后缀。")
    if "/" in stripped or "\\" in stripped:
        raise ValueError("slug 不能包含路径分隔符。")
    if stripped in {".", ".."}:
        raise ValueError("slug 不能是 . 或 ..")


def ensure_pandoc() -> None:
    if shutil.which("pandoc") is None:
        raise RuntimeError(
            "未找到 pandoc。请先安装后重试，例如：brew install pandoc"
        )


def normalize_text(raw: str) -> str:
    text = TAG_RE.sub("", raw)
    text = html.unescape(text)
    return " ".join(text.split())


def slug_from_href(href: str) -> str | None:
    href = href.strip()
    if not href.endswith(".html"):
        return None
    name = Path(href).name
    return name[: -len(".html")]


def extract_entries_from_html_block(block: str, default_created: str) -> dict[str, NoteEntry]:
    entries: dict[str, NoteEntry] = {}

    li_matches = list(LI_RE.finditer(block))
    if li_matches:
        for li_match in li_matches:
            attrs = li_match.group(1)
            inner = li_match.group(2)
            link_match = LINK_RE.search(inner)
            if not link_match:
                continue
            href = html.unescape(link_match.group(1)).strip()
            slug = slug_from_href(href)
            if not slug:
                continue
            title = normalize_text(link_match.group(2))
            created_match = re.search(r'data-created="([^"]+)"', attrs)
            created = created_match.group(1).strip() if created_match else default_created
            entries[slug] = NoteEntry(slug=slug, title=title, created=created)
        return entries

    # 兜底：仅有 <a> 时直接抓取
    for link_match in LINK_RE.finditer(block):
        href = html.unescape(link_match.group(1)).strip()
        slug = slug_from_href(href)
        if not slug:
            continue
        title = normalize_text(link_match.group(2))
        entries[slug] = NoteEntry(slug=slug, title=title, created=default_created)
    return entries


def build_managed_block(entries: list[NoteEntry]) -> str:
    lines = [
        START_MARKER,
        '      <ul id="managed-notes-list">',
    ]
    for entry in entries:
        href = html.escape(f"{entry.slug}.html", quote=True)
        title = html.escape(entry.title)
        created = html.escape(entry.created, quote=True)
        lines.extend(
            [
                f'        <li data-created="{created}">',
                f'          <a href="{href}">',
                f"            {title}",
                "          </a>",
                "        </li>",
            ]
        )
    lines.extend(
        [
            "      </ul>",
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def ensure_managed_block(index_html: str) -> tuple[str, dict[str, NoteEntry]]:
    marker_pattern = re.compile(
        re.escape(START_MARKER) + r"(.*?)" + re.escape(END_MARKER),
        re.DOTALL,
    )
    marker_match = marker_pattern.search(index_html)
    if marker_match:
        block = marker_match.group(1)
        entries = extract_entries_from_html_block(block, default_created=EPOCH_CREATED)
        return index_html, entries

    ul_match = UL_RE.search(index_html)
    if not ul_match:
        raise RuntimeError("未在索引页中找到可迁移的 <ul> 列表。")

    original_ul = ul_match.group(0)
    entries = extract_entries_from_html_block(original_ul, default_created=EPOCH_CREATED)
    managed_block = build_managed_block(list(entries.values()))
    replaced = index_html.replace(original_ul, managed_block, 1)
    return replaced, entries


def replace_managed_block(index_html: str, new_block: str) -> str:
    marker_pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not marker_pattern.search(index_html):
        raise RuntimeError("索引页未找到受管区块标记。")
    return marker_pattern.sub(new_block, index_html, count=1)


def read_category_entries(category: str) -> list[NoteEntry]:
    index_path = CATEGORY_CONFIG[category]["index_path"]
    source = index_path.read_text(encoding="utf-8")
    _, entries = ensure_managed_block(source)
    return list(entries.values())


def build_overview_block() -> str:
    lines = [OVERVIEW_START_MARKER, '      <div class="notes-directory">']
    for category, config in CATEGORY_CONFIG.items():
        entries = read_category_entries(category)
        category_href = html.escape(
            config["index_path"].relative_to(ROOT).as_posix(), quote=True
        )
        lines.extend(
            [
                f'        <article class="notes-category" data-category="{category}">',
                f'          <h2><a href="{category_href}">{html.escape(config["overview_label"])}</a></h2>',
                '          <div class="notes-preview-list">',
            ]
        )
        for entry in entries[:NOTES_PREVIEW_LIMIT]:
            href = html.escape(
                (config["index_path"].parent / f"{entry.slug}.html")
                .relative_to(ROOT)
                .as_posix(),
                quote=True,
            )
            lines.append(
                f'            <h3><a class="notes-preview-title" href="{href}">{html.escape(entry.title)}</a></h3>'
            )
        lines.append("          </div>")
        if len(entries) > NOTES_PREVIEW_LIMIT:
            lines.append(
                f'          <a class="notes-more" href="{category_href}">More …</a>'
            )
        lines.append("        </article>")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.extend(["      </div>", f"      {OVERVIEW_END_MARKER}"])
    return "\n".join(lines)


def update_notes_overview() -> Path:
    if not NOTES_OVERVIEW_PATH.exists():
        raise RuntimeError(f"笔记总览不存在：{NOTES_OVERVIEW_PATH}")
    source = NOTES_OVERVIEW_PATH.read_text(encoding="utf-8")
    marker_pattern = re.compile(
        re.escape(OVERVIEW_START_MARKER)
        + r".*?"
        + re.escape(OVERVIEW_END_MARKER),
        re.DOTALL,
    )
    if not marker_pattern.search(source):
        raise RuntimeError("笔记总览未找到受管预览区块标记。")
    updated = marker_pattern.sub(build_overview_block(), source, count=1)
    NOTES_OVERVIEW_PATH.write_text(updated, encoding="utf-8")
    return NOTES_OVERVIEW_PATH


def render_page(
    title: str,
    breadcrumb_html: str,
    content_html: str,
    last_updated: str,
) -> str:
    if not TEMPLATE_PATH.exists():
        raise RuntimeError(f"模板不存在：{TEMPLATE_PATH}")

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    replacements = {
        "{{title}}": html.escape(title),
        "{{breadcrumb}}": breadcrumb_html,
        "{{content_html}}": content_html,
        "{{last_updated}}": html.escape(last_updated),
    }
    for placeholder, value in replacements.items():
        template = template.replace(placeholder, value)

    unresolved = re.findall(r"{{[^{}]+}}", template)
    if unresolved:
        unresolved_text = ", ".join(sorted(set(unresolved)))
        raise RuntimeError(f"模板中存在未替换占位符：{unresolved_text}")
    return template


def run_pandoc(cmd: list[str], input_text: str | None = None) -> tuple[int, str, str]:
    result = subprocess.run(
        cmd,
        input=input_text,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def sanitize_tex_for_pandoc(raw_tex: str) -> str:
    text = raw_tex.replace("\r\n", "\n").replace("\r", "\n")
    if r"\begin{document}" in text:
        text = text.split(r"\begin{document}", 1)[1]
    if r"\end{document}" in text:
        text = text.split(r"\end{document}", 1)[0]

    text = text.replace(r"\begin{CJK}{UTF8}{gbsn}", "")
    text = text.replace(r"\end{CJK}", "")

    drop_patterns = [
        r"^\s*\\(documentclass|usepackage|geometry|setlength|newcommand|renewcommand|title|author|date|maketitle|tableofcontents|pagestyle|rhead|lhead|cfoot|setcounter|global)\b.*$",
        r"^\s*\\(par|quad)\s*$",
        r"^\s*\\hspace\{[^}]*\}\s*$",
    ]

    kept_lines: list[str] = []
    for line in text.split("\n"):
        if any(re.match(pattern, line) for pattern in drop_patterns):
            continue
        kept_lines.append(line)

    return "\n".join(kept_lines).strip()


def convert_tex_to_html(source: Path) -> str:
    cmd = [
        "pandoc",
        "--from=latex",
        "--to=html5",
        "--mathjax",
        "--wrap=none",
        "--shift-heading-level-by=1",
        str(source),
    ]
    code, html_output, stderr_output = run_pandoc(cmd)
    if code == 0 and html_output:
        return html_output

    # 对带有复杂导言区/CJK环境的 LaTeX 笔记做一次清洗后重试
    raw_tex = source.read_text(encoding="utf-8", errors="ignore")
    cleaned_tex = sanitize_tex_for_pandoc(raw_tex)
    if not cleaned_tex:
        if code != 0:
            raise RuntimeError(f"pandoc 转换失败：\n{stderr_output}")
        raise RuntimeError("pandoc 输出为空，请检查 TeX 内容。")

    stdin_cmd = [
        "pandoc",
        "--from=latex",
        "--to=html5",
        "--mathjax",
        "--wrap=none",
        "--shift-heading-level-by=1",
        "-",
    ]
    fallback_code, fallback_html, fallback_stderr = run_pandoc(stdin_cmd, input_text=cleaned_tex)
    if fallback_code != 0 or not fallback_html:
        if code != 0:
            raise RuntimeError(
                "pandoc 转换失败，且清洗后重试仍失败：\n"
                f"原始错误: {stderr_output}\n"
                f"重试错误: {fallback_stderr}"
            )
        raise RuntimeError(
            "pandoc 原始输出为空，且清洗后重试仍为空。"
        )
    return fallback_html


def write_note_page(category: str, slug: str, page_html: str) -> Path:
    output_path = ROOT / "notes" / category / f"{slug}.html"
    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_MARKER not in existing:
            raise RuntimeError(
                f"slug 冲突：{output_path} 已存在且不是自动生成页面。"
            )
    output_path.write_text(page_html, encoding="utf-8")
    return output_path


def update_index(category: str, slug: str, title: str, created_iso: str) -> Path:
    config = CATEGORY_CONFIG[category]
    index_path = config["index_path"]
    if not index_path.exists():
        raise RuntimeError(f"分类索引不存在：{index_path}")

    original = index_path.read_text(encoding="utf-8")
    working, entries = ensure_managed_block(original)

    old = entries.get(slug)
    created = old.created if old else created_iso
    entries[slug] = NoteEntry(slug=slug, title=title, created=created)

    sorted_entries = sorted(
        entries.values(),
        key=lambda item: (item.created, item.title),
        reverse=True,
    )
    new_block = build_managed_block(sorted_entries)
    updated = replace_managed_block(working, new_block)
    index_path.write_text(updated, encoding="utf-8")
    return index_path


def main() -> int:
    args = parse_args()
    source = Path(args.source).expanduser()

    try:
        validate_slug(args.slug)
        if not source.exists():
            raise FileNotFoundError(f"source 文件不存在：{source}")
        if source.suffix.lower() != ".tex":
            raise ValueError("source 必须是 .tex 文件。")

        ensure_pandoc()
        content_html = convert_tex_to_html(source)

        config = CATEGORY_CONFIG[args.category]
        breadcrumb = (
            f'<a href="{config["index_href"]}">{html.escape(config["label"])}</a> · '
            f"<span>{html.escape(args.title)}</span>"
        )
        now = dt.datetime.now().astimezone()
        created_iso = now.isoformat(timespec="seconds")
        last_updated = now.date().isoformat()

        page_html = render_page(
            title=args.title,
            breadcrumb_html=breadcrumb,
            content_html=content_html,
            last_updated=last_updated,
        )
        output_path = write_note_page(args.category, args.slug, page_html)
        index_path = update_index(args.category, args.slug, args.title, created_iso)
        overview_path = update_notes_overview()

        print(f"[OK] Generated note: {output_path}")
        print(f"[OK] Updated index: {index_path}")
        print(f"[OK] Updated overview: {overview_path}")
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
