#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = ROOT / "templates" / "note_page.html"
NOTES_OVERVIEW_PATH = ROOT / "notes.html"
START_MARKER = "<!-- AUTO-NOTES:START -->"
END_MARKER = "<!-- AUTO-NOTES:END -->"
OVERVIEW_START_MARKER = "<!-- NOTES-PREVIEW:START -->"
OVERVIEW_END_MARKER = "<!-- NOTES-PREVIEW:END -->"
GENERATED_MARKER = "<!-- Generated by sync_tex_note.py -->"
CATALOG_START_MARKER = "  // NOTE-CATALOG:START"
CATALOG_END_MARKER = "  // NOTE-CATALOG:END"
NOTE_SCRIPT_PATH = ROOT / "assets" / "note-page.js"
EPOCH_CREATED = "1970-01-01T00:00:00+00:00"
NOTES_PREVIEW_LIMIT = 3

CATEGORY_CONFIG = {
    "dft": {
        "index_path": ROOT / "notes" / "dft" / "index.html",
        "index_href": "index.html",
        "label": "notes on DFT calculations",
        "overview_label": "DFT calculations",
    },
    "tb": {
        "index_path": ROOT / "notes" / "tb" / "index.html",
        "index_href": "index.html",
        "label": "notes on Tight-binding models",
        "overview_label": "Tight-binding calculations",
    },
    "other": {
        "index_path": ROOT / "notes" / "other" / "index.html",
        "index_href": "index.html",
        "label": "other notes",
        "overview_label": "Other notes",
    },
}

LINK_RE = re.compile(r'<a\s+href="([^"]+)">\s*(.*?)\s*</a>', re.IGNORECASE | re.DOTALL)
LI_RE = re.compile(r"<li\b([^>]*)>(.*?)</li>", re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
UL_RE = re.compile(r"<ul\b[^>]*>.*?</ul>", re.IGNORECASE | re.DOTALL)


@dataclass
class NoteEntry:
    slug: str
    title: str
    created: str


class ExcerptParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.main_depth = 0
        self.skip_depth = 0
        self.current_tag: str | None = None
        self.buffer: list[str] = []
        self.paragraphs: list[str] = []
        self.headings: list[str] = []
        self.heading_count_at_first_paragraph: int | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "main":
            self.main_depth += 1
        if tag in {"script", "style"}:
            self.skip_depth += 1
        if self.main_depth and not self.skip_depth and tag in {"p", "h2"}:
            self.current_tag = tag
            self.buffer = []

    def handle_endtag(self, tag: str) -> None:
        if tag == self.current_tag:
            value = " ".join(" ".join(self.buffer).split())
            if value:
                target = self.paragraphs if tag == "p" else self.headings
                target.append(value)
                if tag == "p" and self.heading_count_at_first_paragraph is None:
                    self.heading_count_at_first_paragraph = len(self.headings)
            self.current_tag = None
            self.buffer = []
        if tag in {"script", "style"} and self.skip_depth:
            self.skip_depth -= 1
        if tag == "main" and self.main_depth:
            self.main_depth -= 1

    def handle_data(self, data: str) -> None:
        if self.current_tag and not self.skip_depth:
            self.buffer.append(data)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert TeX notes to HTML pages and update category index."
    )
    parser.add_argument("--category", required=True, choices=sorted(CATEGORY_CONFIG.keys()))
    parser.add_argument("--source", required=True, help="Path to the original .tex source file")
    parser.add_argument("--translation-source", required=True, help="Path to the translated .tex source file")
    parser.add_argument("--source-lang", required=True, choices=("zh-CN", "en"))
    parser.add_argument("--title", required=True, help="Original title in index and note page")
    parser.add_argument("--translation-title", required=True, help="Translated note-page title")
    parser.add_argument("--slug", required=True, help="Output file slug (without .html)")
    parser.add_argument(
        "--published-date",
        help="First publication date in YYYY-MM-DD; existing notes reuse their stored date",
    )
    return parser.parse_args()


def validate_slug(slug: str) -> None:
    stripped = slug.strip()
    if not stripped:
        raise ValueError("slug 不能为空。")
    if stripped.endswith(".html"):
        raise ValueError("slug 不需要带 .html 后缀。")
    if "/" in stripped or "\\" in stripped:
        raise ValueError("slug 不能包含路径分隔符。")
    if stripped in {".", ".."}:
        raise ValueError("slug 不能是 . 或 ..")


def ensure_pandoc() -> None:
    if shutil.which("pandoc") is None:
        raise RuntimeError(
            "未找到 pandoc。请先安装后重试，例如：brew install pandoc"
        )


def normalize_text(raw: str) -> str:
    text = TAG_RE.sub("", raw)
    text = html.unescape(text)
    text = "".join(
        character
        for character in text
        if ord(character) >= 32 or character in "\t\n\r"
    )
    return " ".join(text.split())


def slug_from_href(href: str) -> str | None:
    href = href.strip()
    if not href.endswith(".html"):
        return None
    name = Path(href).name
    return name[: -len(".html")]


def extract_entries_from_html_block(block: str, default_created: str) -> dict[str, NoteEntry]:
    entries: dict[str, NoteEntry] = {}

    li_matches = list(LI_RE.finditer(block))
    if li_matches:
        for li_match in li_matches:
            attrs = li_match.group(1)
            inner = li_match.group(2)
            link_match = LINK_RE.search(inner)
            if not link_match:
                continue
            href = html.unescape(link_match.group(1)).strip()
            slug = slug_from_href(href)
            if not slug:
                continue
            title = normalize_text(link_match.group(2))
            created_match = re.search(r'data-created="([^"]+)"', attrs)
            created = created_match.group(1).strip() if created_match else default_created
            entries[slug] = NoteEntry(slug=slug, title=title, created=created)
        return entries

    # 兜底：仅有 <a> 时直接抓取
    for link_match in LINK_RE.finditer(block):
        href = html.unescape(link_match.group(1)).strip()
        slug = slug_from_href(href)
        if not slug:
            continue
        title = normalize_text(link_match.group(2))
        entries[slug] = NoteEntry(slug=slug, title=title, created=default_created)
    return entries


def build_managed_block(entries: list[NoteEntry]) -> str:
    lines = [
        START_MARKER,
        '      <ul id="managed-notes-list">',
    ]
    for entry in entries:
        href = html.escape(f"{entry.slug}.html", quote=True)
        title = html.escape(entry.title)
        created = html.escape(entry.created, quote=True)
        lines.extend(
            [
                f'        <li data-created="{created}">',
                f'          <a href="{href}">',
                f"            {title}",
                "          </a>",
                "        </li>",
            ]
        )
    lines.extend(
        [
            "      </ul>",
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def ensure_managed_block(index_html: str) -> tuple[str, dict[str, NoteEntry]]:
    marker_pattern = re.compile(
        re.escape(START_MARKER) + r"(.*?)" + re.escape(END_MARKER),
        re.DOTALL,
    )
    marker_match = marker_pattern.search(index_html)
    if marker_match:
        block = marker_match.group(1)
        entries = extract_entries_from_html_block(block, default_created=EPOCH_CREATED)
        return index_html, entries

    ul_match = UL_RE.search(index_html)
    if not ul_match:
        raise RuntimeError("未在索引页中找到可迁移的 <ul> 列表。")

    original_ul = ul_match.group(0)
    entries = extract_entries_from_html_block(original_ul, default_created=EPOCH_CREATED)
    managed_block = build_managed_block(list(entries.values()))
    replaced = index_html.replace(original_ul, managed_block, 1)
    return replaced, entries


def replace_managed_block(index_html: str, new_block: str) -> str:
    marker_pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not marker_pattern.search(index_html):
        raise RuntimeError("索引页未找到受管区块标记。")
    return marker_pattern.sub(new_block, index_html, count=1)


def read_category_entries(category: str) -> list[NoteEntry]:
    index_path = CATEGORY_CONFIG[category]["index_path"]
    source = index_path.read_text(encoding="utf-8")
    _, entries = ensure_managed_block(source)
    return list(entries.values())


def excerpt_from_note(path: Path) -> str:
    parser = ExcerptParser()
    parser.feed(path.read_text(encoding="utf-8", errors="ignore"))
    parser.close()

    if (parser.heading_count_at_first_paragraph or 0) >= 3:
        return " · ".join(parser.headings[:3])

    def plain_inline_math(match: re.Match[str]) -> str:
        value = match.group(1)
        value = re.sub(
            r"\\(?:texttt|mathbf|mathrm|text)\{([^{}]+)\}",
            r"\1",
            value,
        )
        value = re.sub(r"\\sqrt\{([^{}]+)\}", r"√(\1)", value)
        value = value.replace(r"\approx", "≈").replace(r"\lt", "<")
        value = re.sub(r"\\ln\b", "ln", value)
        value = re.sub(r"\\[A-Za-z]+", "", value)
        return re.sub(r"[{}]", "", value)

    for paragraph in parser.paragraphs:
        if "http://" in paragraph or "https://" in paragraph:
            continue
        before_display_math = re.split(r"\\begin\{", paragraph, maxsplit=1)[0].strip()
        if len(before_display_math) >= 8:
            paragraph = before_display_math
        if len(paragraph) < 8:
            continue
        paragraph = re.sub(r"\$([^$]+)\$", plain_inline_math, paragraph)
        paragraph = re.sub(r"\\[A-Za-z]+", "", paragraph)
        paragraph = re.sub(r"[{}]", "", paragraph)
        paragraph = " ".join(paragraph.split())
        paragraph = re.sub(r"\s+([，。,.])", r"\1", paragraph)
        paragraph = re.sub(r",?\s*e\.g\.\.?$", ".", paragraph)
        if len(paragraph) >= 8:
            return paragraph
    if parser.headings:
        return " · ".join(parser.headings[:3])
    raise RuntimeError(f"无法从笔记正文提取摘要：{path}")


def build_overview_block() -> str:
    lines = [OVERVIEW_START_MARKER, '      <div class="notes-directory">']
    for category, config in CATEGORY_CONFIG.items():
        entries = read_category_entries(category)
        category_href = html.escape(
            config["index_path"].relative_to(ROOT).as_posix(), quote=True
        )
        lines.extend(
            [
                f'        <article class="notes-category" data-category="{category}">',
                f'          <h2><a href="{category_href}">{html.escape(config["overview_label"])}</a></h2>',
                '          <div class="notes-preview-list">',
            ]
        )
        for entry in entries[:NOTES_PREVIEW_LIMIT]:
            note_path = config["index_path"].parent / f"{entry.slug}.html"
            href = html.escape(note_path.relative_to(ROOT).as_posix(), quote=True)
            excerpt = html.escape(excerpt_from_note(note_path))
            lines.extend(
                [
                    '            <div class="notes-preview">',
                    f'              <h3><a class="notes-preview-title" href="{href}">{html.escape(entry.title)}</a></h3>',
                    f'              <p class="notes-excerpt">{excerpt}</p>',
                    "            </div>",
                ]
            )
        lines.append("          </div>")
        if len(entries) > NOTES_PREVIEW_LIMIT:
            lines.append(
                f'          <a class="notes-more" href="{category_href}">More …</a>'
            )
        lines.append("        </article>")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.extend(["      </div>", f"      {OVERVIEW_END_MARKER}"])
    return "\n".join(lines)


def update_notes_overview() -> Path:
    if not NOTES_OVERVIEW_PATH.exists():
        raise RuntimeError(f"笔记总览不存在：{NOTES_OVERVIEW_PATH}")
    source = NOTES_OVERVIEW_PATH.read_text(encoding="utf-8")
    marker_pattern = re.compile(
        re.escape(OVERVIEW_START_MARKER)
        + r".*?"
        + re.escape(OVERVIEW_END_MARKER),
        re.DOTALL,
    )
    if not marker_pattern.search(source):
        raise RuntimeError("笔记总览未找到受管预览区块标记。")
    updated = marker_pattern.sub(build_overview_block(), source, count=1)
    NOTES_OVERVIEW_PATH.write_text(updated, encoding="utf-8")
    return NOTES_OVERVIEW_PATH


def note_page_metadata(path: Path) -> tuple[str, str, str]:
    source = path.read_text(encoding="utf-8")
    lang_match = re.search(r'<html\b[^>]*\blang="([^"]+)"', source, re.IGNORECASE)
    alternate_match = re.search(
        r'<html\b[^>]*\bdata-note-alternate="([^"]+)"',
        source,
        re.IGNORECASE,
    )
    title_match = re.search(r"<h1\b[^>]*>(.*?)</h1>", source, re.IGNORECASE | re.DOTALL)
    if not lang_match or not alternate_match or not title_match:
        raise RuntimeError(f"无法读取双语笔记元数据：{path}")
    title = normalize_text(title_match.group(1))
    return lang_match.group(1), html.unescape(alternate_match.group(1)), title


def build_note_catalog() -> dict[str, list[dict[str, str]]]:
    catalog: dict[str, list[dict[str, str]]] = {}
    for category in CATEGORY_CONFIG:
        items: list[dict[str, str]] = []
        category_dir = CATEGORY_CONFIG[category]["index_path"].parent
        for entry in read_category_entries(category):
            original_path = category_dir / f"{entry.slug}.html"
            original_lang, alternate_filename, original_title = note_page_metadata(
                original_path
            )
            alternate_path = category_dir / alternate_filename
            alternate_lang, _, alternate_title = note_page_metadata(alternate_path)
            by_lang = {
                original_lang: (original_path.name, original_title),
                alternate_lang: (alternate_path.name, alternate_title),
            }
            if "zh-CN" not in by_lang or "en" not in by_lang:
                raise RuntimeError(f"双语笔记语言配对不完整：{original_path}")
            items.append(
                {
                    "zh": by_lang["zh-CN"][0],
                    "en": by_lang["en"][0],
                    "zhTitle": by_lang["zh-CN"][1],
                    "enTitle": by_lang["en"][1],
                }
            )
        catalog[category] = items
    return catalog


def update_note_catalog() -> Path:
    if not NOTE_SCRIPT_PATH.exists():
        raise RuntimeError(f"笔记交互脚本不存在：{NOTE_SCRIPT_PATH}")
    source = NOTE_SCRIPT_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(CATALOG_START_MARKER)
        + r".*?"
        + re.escape(CATALOG_END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(source):
        raise RuntimeError("笔记交互脚本缺少受管导航目录标记。")
    serialized = json.dumps(build_note_catalog(), ensure_ascii=False, indent=2)
    indented = "\n".join(f"  {line}" for line in serialized.splitlines())
    block = (
        f"{CATALOG_START_MARKER}\n"
        f"  const noteCatalog = {indented.lstrip()};\n"
        f"{CATALOG_END_MARKER}"
    )
    NOTE_SCRIPT_PATH.write_text(pattern.sub(block, source, count=1), encoding="utf-8")
    return NOTE_SCRIPT_PATH


def render_page(
    title: str,
    breadcrumb_html: str,
    content_html: str,
    published_date: str,
    page_lang: str,
    alternate_filename: str,
) -> str:
    if not TEMPLATE_PATH.exists():
        raise RuntimeError(f"模板不存在：{TEMPLATE_PATH}")

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    alternate_lang = "en" if page_lang == "zh-CN" else "zh-CN"
    language_options = (
        '<span lang="zh-CN" aria-current="page">中文</span>\n'
        f'            <a class="language-switch" href="{html.escape(alternate_filename, quote=True)}" '
        f'hreflang="{alternate_lang}">English</a>'
        if page_lang == "zh-CN"
        else (
            f'<a class="language-switch" href="{html.escape(alternate_filename, quote=True)}" '
            'hreflang="zh-CN">中文</a>\n'
            '            <span lang="en" aria-current="page">English</span>'
        )
    )
    replacements = {
        "{{title}}": html.escape(title),
        "{{breadcrumb}}": breadcrumb_html,
        "{{content_html}}": content_html,
        "{{published_date}}": html.escape(published_date),
        "{{page_lang}}": html.escape(page_lang, quote=True),
        "{{alternate_filename}}": html.escape(alternate_filename, quote=True),
        "{{alternate_lang}}": alternate_lang,
        "{{language_options}}": language_options,
        "{{published_label}}": "发布于" if page_lang == "zh-CN" else "Published",
        "{{contents_label}}": "目录" if page_lang == "zh-CN" else "Contents",
    }
    for placeholder, value in replacements.items():
        template = template.replace(placeholder, value)

    unresolved = re.findall(r"{{[^{}]+}}", template)
    if unresolved:
        unresolved_text = ", ".join(sorted(set(unresolved)))
        raise RuntimeError(f"模板中存在未替换占位符：{unresolved_text}")
    return template


def resolve_published_date(
    category: str,
    slug: str,
    requested: str | None,
    now: dt.datetime,
) -> tuple[str, str]:
    entries = {entry.slug: entry for entry in read_category_entries(category)}
    existing = entries.get(slug)
    if existing and existing.created != EPOCH_CREATED:
        return existing.created[:10], existing.created

    if requested:
        try:
            date_value = dt.date.fromisoformat(requested)
        except ValueError as exc:
            raise ValueError("--published-date 必须是 YYYY-MM-DD。") from exc
        local_time = dt.datetime.combine(
            date_value,
            dt.time.min,
            tzinfo=now.tzinfo,
        )
        return date_value.isoformat(), local_time.isoformat(timespec="seconds")

    return now.date().isoformat(), now.isoformat(timespec="seconds")


def run_pandoc(cmd: list[str], input_text: str | None = None) -> tuple[int, str, str]:
    result = subprocess.run(
        cmd,
        input=input_text,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def sanitize_tex_for_pandoc(raw_tex: str) -> str:
    text = raw_tex.replace("\r\n", "\n").replace("\r", "\n")
    if r"\begin{document}" in text:
        text = text.split(r"\begin{document}", 1)[1]
    if r"\end{document}" in text:
        text = text.split(r"\end{document}", 1)[0]

    text = text.replace(r"\begin{CJK}{UTF8}{gbsn}", "")
    text = text.replace(r"\end{CJK}", "")

    drop_patterns = [
        r"^\s*\\(documentclass|usepackage|geometry|setlength|newcommand|renewcommand|title|author|date|maketitle|tableofcontents|pagestyle|rhead|lhead|cfoot|setcounter|global)\b.*$",
        r"^\s*\\(par|quad)\s*$",
        r"^\s*\\hspace\{[^}]*\}\s*$",
    ]

    kept_lines: list[str] = []
    for line in text.split("\n"):
        if any(re.match(pattern, line) for pattern in drop_patterns):
            continue
        kept_lines.append(line)

    return "\n".join(kept_lines).strip()


def convert_tex_to_html(source: Path) -> str:
    cmd = [
        "pandoc",
        "--from=latex",
        "--to=html5",
        "--mathjax",
        "--wrap=none",
        "--shift-heading-level-by=1",
        str(source),
    ]
    code, html_output, stderr_output = run_pandoc(cmd)
    if code == 0 and html_output:
        return html_output

    # 对带有复杂导言区/CJK环境的 LaTeX 笔记做一次清洗后重试
    raw_tex = source.read_text(encoding="utf-8", errors="ignore")
    cleaned_tex = sanitize_tex_for_pandoc(raw_tex)
    if not cleaned_tex:
        if code != 0:
            raise RuntimeError(f"pandoc 转换失败：\n{stderr_output}")
        raise RuntimeError("pandoc 输出为空，请检查 TeX 内容。")

    stdin_cmd = [
        "pandoc",
        "--from=latex",
        "--to=html5",
        "--mathjax",
        "--wrap=none",
        "--shift-heading-level-by=1",
        "-",
    ]
    fallback_code, fallback_html, fallback_stderr = run_pandoc(stdin_cmd, input_text=cleaned_tex)
    if fallback_code != 0 or not fallback_html:
        if code != 0:
            raise RuntimeError(
                "pandoc 转换失败，且清洗后重试仍失败：\n"
                f"原始错误: {stderr_output}\n"
                f"重试错误: {fallback_stderr}"
            )
        raise RuntimeError(
            "pandoc 原始输出为空，且清洗后重试仍为空。"
        )
    return fallback_html


def write_note_page(category: str, filename: str, page_html: str) -> Path:
    output_path = ROOT / "notes" / category / filename
    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_MARKER not in existing:
            raise RuntimeError(
                f"slug 冲突：{output_path} 已存在且不是自动生成页面。"
            )
    output_path.write_text(page_html, encoding="utf-8")
    return output_path


def update_index(category: str, slug: str, title: str, created_iso: str) -> Path:
    config = CATEGORY_CONFIG[category]
    index_path = config["index_path"]
    if not index_path.exists():
        raise RuntimeError(f"分类索引不存在：{index_path}")

    original = index_path.read_text(encoding="utf-8")
    working, entries = ensure_managed_block(original)

    old = entries.get(slug)
    created = old.created if old else created_iso
    entries[slug] = NoteEntry(slug=slug, title=title, created=created)

    sorted_entries = sorted(
        entries.values(),
        key=lambda item: (item.created, item.title),
        reverse=True,
    )
    new_block = build_managed_block(sorted_entries)
    updated = replace_managed_block(working, new_block)
    index_path.write_text(updated, encoding="utf-8")
    return index_path


def main() -> int:
    args = parse_args()
    source = Path(args.source).expanduser()

    try:
        validate_slug(args.slug)
        translation_source = Path(args.translation_source).expanduser()
        for label, candidate in (
            ("source", source),
            ("translation-source", translation_source),
        ):
            if not candidate.exists():
                raise FileNotFoundError(f"{label} 文件不存在：{candidate}")
            if candidate.suffix.lower() != ".tex":
                raise ValueError(f"{label} 必须是 .tex 文件。")

        ensure_pandoc()
        content_html = convert_tex_to_html(source)
        translated_content_html = convert_tex_to_html(translation_source)

        config = CATEGORY_CONFIG[args.category]
        original_breadcrumb = (
            f'<a href="{config["index_href"]}">{html.escape(config["label"])}</a> · '
            f"<span>{html.escape(args.title)}</span>"
        )
        translation_breadcrumb = (
            f'<a href="{config["index_href"]}">{html.escape(config["label"])}</a> · '
            f"<span>{html.escape(args.translation_title)}</span>"
        )
        now = dt.datetime.now().astimezone()
        published_date, created_iso = resolve_published_date(
            args.category,
            args.slug,
            args.published_date,
            now,
        )
        translation_suffix = "en" if args.source_lang == "zh-CN" else "zh"
        translated_filename = f"{args.slug}.{translation_suffix}.html"

        original_html = render_page(
            title=args.title,
            breadcrumb_html=original_breadcrumb,
            content_html=content_html,
            published_date=published_date,
            page_lang=args.source_lang,
            alternate_filename=translated_filename,
        )
        translated_lang = "en" if args.source_lang == "zh-CN" else "zh-CN"
        translated_html = render_page(
            title=args.translation_title,
            breadcrumb_html=translation_breadcrumb,
            content_html=translated_content_html,
            published_date=published_date,
            page_lang=translated_lang,
            alternate_filename=f"{args.slug}.html",
        )
        output_path = write_note_page(args.category, f"{args.slug}.html", original_html)
        translated_path = write_note_page(args.category, translated_filename, translated_html)
        index_path = update_index(args.category, args.slug, args.title, created_iso)
        overview_path = update_notes_overview()
        catalog_path = update_note_catalog()

        print(f"[OK] Generated note: {output_path}")
        print(f"[OK] Generated translation: {translated_path}")
        print(f"[OK] Updated index: {index_path}")
        print(f"[OK] Updated note navigation: {catalog_path}")
        print(f"[OK] Updated overview: {overview_path}")
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
